# Generated by Django 2.0 on 2017-12-31 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_text', models.CharField(max_length=200)),
                ('times', models.IntegerField(default=0)),
                ('result', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_text', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(verbose_name='date createded')),
            ],
        ),
        migrations.AddField(
            model_name='algorithm',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithms.Type'),
        ),
    ]
